### ISSUE TITLE
Demo Play ?

### ISSUE THREAD

**Issue by ZenMoore** [wty-ustc/HairCLIP#1]
Hi. 🤗 
This is an awesome work. 👍 
Thanks for all of you, the contributors. 🌹 
I am wondering if you could tell me if you have any plan to make one demo public on huggingface/spaces, etc. 🤔 ？

**Comment by wty-ustc** [comment]
We plan to release the code and pre-trained models with the paper, but the paper is still under review, so please be patient.

**Comment by semi-supervised-paper** [comment]
@wty-ustc  A great job! I notice that the paper has been released on arxiv. Could you please release the code ?

**Comment by wty-ustc** [comment]
> @wty-ustc A great job! I notice that the paper has been released on arxiv. Could you please release the code ?

Please be patient until our paper is officially accepted.
