### ISSUE TITLE
Except hair coloe change only, but hair style of some results are change 

### ISSUE THREAD

**Issue by kasim0226** [wty-ustc/HairCLIP#10]
I want to change  hair color on FFHQ data, however hairstyle of some of results are change.
Did I do wrong?
The following is my command

python scripts/inference.py \
--exp_dir=./experiment \
--checkpoint_path=../pretrained_models/hairclip.pt \
--latents_test_path=./latents.pt \
--editing_type=color \
--input_type=text \
--color_description=red

![00001-0000-red hair](https://user-images.githubusercontent.com/5126656/159231496-51df5fdf-67eb-467c-9eb1-fa384d42b69d.jpg)

**Comment by wty-ustc** [comment]
It looks like your run is fine. I doubt if there is some gap between the data, you can test the CelebA-HQ data to check if there is any problem, if not, you may need to retrain a HairCLIP on the FFHQ dataset for better results.

**Comment by wty-ustc** [comment]
I just checked the test results and found that for people with very short hair there may be a problem with visual hairstyle changes due to non-uniform coloring. For other lengths of hair there is no such problem.

**Comment by wty-ustc** [comment]
However, another version of the training does not have this problem, you can retrain HairCLIP and maybe the problem will disappear.

**Comment by kasim0226** [comment]
Got it. Thank you for your reply.

If I only want color change, would the follwing setting help when I train new model?
--hairstyle_manipulation_prob=0 \
--color_manipulation_prob=1 \
--both_manipulation_prob=0 \
--color_text_manipulation_prob=1 \

**Comment by wty-ustc** [comment]
Yes, and it probably converges very fast. Probably tens of thousands of iterations later it's already trained.

**Comment by kasim0226** [comment]
Thank you for your suguesstions.

**Comment by wty-ustc** [comment]
Have fun with it!
