### ISSUE TITLE
Can I use my own image test?

### ISSUE THREAD

**Issue by liuzhuangyuan** [wty-ustc/HairCLIP#12]
Hello, can I use my own image for the resend test, I found that the input was test_face.pt (test data set ?) file, and I did not find the input image content in the code, The only thing that feels like an input image is w(w=torch.Size([1, 18, 512])), But it's not the size of a picture

**Comment by wty-ustc** [comment]
Sure, but you need to use [e4e](https://github.com/omertov/encoder4editing) to get the latent code of the image.
