### ISSUE TITLE
Hosting HairCLIP model

### ISSUE THREAD

**Issue by ouhenio** [wty-ustc/HairCLIP#13]
Hi!

First off, thank you for your work!

I'm trying to create a Colab Notebook to play with your model, but since the weights and stuff are hosted inside google drive, the download limits seems to restrict me from simply downloading it with `gdown` or `wget`. 

Could I download it and move it to another hosting service (i.e archive.org) to avoid this issue? Of course, I would add all the references to all the authors and parties involved.

Again, thanks for your work!

**Comment by wty-ustc** [comment]
OK
