### ISSUE TITLE
Hairstyles can only show so much

### ISSUE THREAD

**Issue by ZziTaiLeo** [wty-ustc/HairCLIP#14]
First of all , thanks for you excellent work!
There are many hairstyles in hairstyle.txt, but actually I found only a few styles in result images after trying all styles. More or less repeat the following images.
- cornrows cut hairstyle
![image](https://user-images.githubusercontent.com/42994566/160222645-8a50651e-d8e9-431f-b96f-b5853721e7f4.png)

- crew cut hairstyle
![image](https://user-images.githubusercontent.com/42994566/160222622-bf4c0a6e-2158-407b-8f13-26d2d67a3ff8.png)
(the points on left glasses in right image is mouse)

the following is my command:
``` 
python scripts/inference.py 
--exp_dir=../result/test_1/
--checkpoint_path=../pretrained_models/hairclip.pt
--latents_test_path=../inference_data/test_1/latent.pt
--editing_type=hairstyle
--input_type=text
--hairstyle_description="hairstyle_list.txt"
```

What's the problem? Should I train with my own dataset?

I list some hairstyles which have the same effect:
- 1. the same as cornrows: crown braid hairstyle, dreadlocks hairstyle, finger waves hairstyle, french braid hairstyle and so on.
- 2. the same as crew cut hairstyle: caesar cut hairstyle,  dido flip hairstyle, extensions hairstyle, fade hairstyle, fauxhawk hairstyle, frosted tops hairstyle ,full crown hairstyle, harvard clip hairstyle, high and tigh hairstyle, hime cut hairstyle, hi-top fade hairstyle and so son.

**Comment by wty-ustc** [comment]
1. Some of the text hairstyle descriptions are very similar.
2. As stated in the limitations section of our paper, no reasonable results can be given for descriptions that are not in the domains of StyleGAN. For example, some hairstyles are only available for ladies.
3. You can reduce the number of hairstyle text descriptions to retrain HairCLIP, the training process may take less than 1 day, and this approach may be effective.
