### ISSUE TITLE
How to run predict.py

### ISSUE THREAD

**Issue by panghongwei17** [wty-ustc/HairCLIP#19]
HI ，Thank you for your work
   
In line 11, （from cog import BasePredictor, Path, Input）this sentence means ？
I have a red wavy line here

**Comment by chenxwh** [comment]
Hi, [Cog](https://github.com/replicate/cog) is the open source tool used realising the replicate demo, please check the document for installation details or this [PR](https://github.com/wty-ustc/HairCLIP/pull/16#issue-1182227198) for reference. With `cog.yaml` and `predict.py`, you can use Cog to build your own web demo and docker image. However for HairCLIP it is implemented by us [here](https://replicate.com/wty-ustc/hairclip) with customised image input, you can try the web demo directly without the need to run `predict.py` :) Hope it helps.

**Comment by panghongwei17** [comment]
> Hi, [Cog](https://github.com/replicate/cog) is the open source tool used realising the replicate demo, please check the document for installation details or this [PR](https://github.com/wty-ustc/HairCLIP/pull/16#issue-1182227198) for reference. With `cog.yaml` and `predict.py`, you can use Cog to build your own web demo and docker image. However for HairCLIP it is implemented by us [here](https://replicate.com/wty-ustc/hairclip) with customised image input, you can try the web demo directly without the need to run `predict.py` :) Hope it helps.

Hi，
Thank you for your answer.
Oh, I see.
I also want to ask you a question. Does this work support inputting an original hairstyle image and a reference hairstyle image instead of text input, and then returning the result? If yes, where can I modify this part because I see inference.py, the test data is encoded into latents
Thank you again for your work!

**Comment by chenxwh** [comment]
The `predict` function in `predict.py` accepts any input and any `Output` object as you define them (see this [doc](https://github.com/replicate/cog/blob/main/docs/python.md) for more details, feel free to play with it :)

**Comment by panghongwei17** [comment]
> The `predict` function in `predict.py` accepts any input and any `Output` object as you define them (see this [doc](https://github.com/replicate/cog/blob/main/docs/python.md) for more details, feel free to play with it :)

OK, thank you for your patience and guidance.
Have a nice day！
