### ISSUE TITLE
About modulation module

### ISSUE THREAD

**Issue by janchen0611** [wty-ustc/HairCLIP#2]
Hi, 
Great work!
But I have a question about the modulation module of mapper network.
I assume the dimension of x and e should be 1x1xC.
If so, what is the mean and std of x? channel-wise average?
And how about the output dimensions of fr(e) and fb(e)? 

Thanks.

**Comment by wty-ustc** [comment]
Yes. The mean and standard deviation of x are implemented by layernorm without learnable affine parameters. The output dimensions are both 1x1xC. Please follow this repository for the exact implementation, we will release the code and pre-trained model after the paper is accepted.

**Comment by janchen0611** [comment]
Thanks! 
Looking forward to your code and model.
