### ISSUE TITLE
about pretrained unet infer

### ISSUE THREAD

**Issue by eeric** [wty-ustc/HairCLIP#7]
mask_512 = (torch.unsqueeze(torch.max(labels_predict, 1)[1], 1)==13).float()
1.why hair equal 13, bg not equal 13?
2.unet infer results that have 19 channels, what did they means?

**Comment by wty-ustc** [comment]
Please refer to [Face parsing](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing).

**Comment by eeric** [comment]
ok, thanks.
